devices:
  samplerate: 44100
  chunksize: 1024
  capture:
    type: Alsa
    device: "plughw:Loopback,1,0"
    channels: 2
    format: S16LE
  playback:
    type: Alsa
    device: "plughw:Loopback,0,1"
    channels: 2
    format: S16LE

mixers:
  stereo:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: 0
            inverted: false

filters:
  main_volume:
    type: Volume
    parameters:
      fader: -20.0 # Volume initial en dB
      ramp_time: 200

pipeline:
  - type: Mixer
    name: stereo
  - type: Filter
    name: main_volume
