description: null
devices:
  adjust_period: 10
  capture:
    channels: 2
    device: hw:CARD=wm8960soundcard,DEV=0
    format: S16LE
    type: Alsa
  capture_samplerate: 48000
  chunksize: 1024
  enable_rate_adjust: true
  playback:
    channels: 2
    device: hw:CARD=wm8960soundcard,DEV=0
    format: S16LE
    type: Alsa
  queuelimit: 2048
  rate_measure_interval: null
  resampler: null
  samplerate: 48000
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: 1024
  volume_ramp_time: null
filters:
  convolution:
    description: null
    parameters:
      channel: 1
      filename: ../coeffs/coeffs1.wav
      type: Wav
    type: Conv
  delay:
    description: null
    parameters:
      delay: 0
      subsample: false
      unit: ms
    type: Delay
  limiter:
    description: null
    parameters:
      clip_limit: -3
      soft_clip: true
    type: Limiter
  input-lowpass:
    description: null
    parameters:
      freq: 800
      order: 2
      type: ButterworthLowpass
    type: BiquadCombo
  output-lowpass:
    description: null
    parameters:
      freq: 2000
      order: 2
      type: ButterworthLowpass
    type: BiquadCombo
mixers:
  Unnamed Mixer 1:
    channels:
      in: 2
      out: 2
    description: null
    mapping:
      - dest: 1
        mute: false
        sources:
          - channel: 0
            gain: 0
            inverted: false
            mute: false
            scale: dB
      - dest: 0
        mute: false
        sources:
          - channel: 0
            gain: 0
            inverted: false
            mute: false
            scale: dB
pipeline:
  - bypassed: null
    channels: [0]
    description: null
    names:
      - limiter
    type: Filter
  - bypassed: null
    channels: [0]
    description: null
    names:
      - input-lowpass
    type: Filter
  - bypassed: null
    channels: [0]
    description: null
    names:
      - delay
    type: Filter
  - bypassed: null
    channels: [0]
    description: null
    names:
      - convolution
    type: Filter
  - bypassed: null
    channels: [0]
    description: null
    names:
      - output-lowpass
    type: Filter
  - bypassed: null
    description: null
    name: Unnamed Mixer 1
    type: Mixer
processors: {}
title: My Favorite Hall
