description: null
devices:
  adjust_period: null
  capture:
    channels: 2
    device: hw:CARD=wm8960soundcard,DEV=0
    format: S16LE
    type: Alsa
  capture_samplerate: 48000
  chunksize: 300
  enable_rate_adjust: null
  playback:
    channels: 2
    device: hw:CARD=wm8960soundcard,DEV=0
    format: S16LE
    type: Alsa
  queuelimit: null
  rate_measure_interval: null
  resampler: null
  samplerate: 44100
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_ramp_time: null
filters:
  Convolution:
    description: null
    parameters:
      channel: 1
      filename: ../coeffs/1 Halls 16 Amsterdam Hall  M-to-S.wav
      type: Wav
    type: Conv
  Delai:
    description: null
    parameters:
      delay: 0
      subsample: false
      unit: ms
    type: Delay
  Limiteur:
    description: null
    parameters:
      clip_limit: -3
      soft_clip: true
    type: Limiter
  "Passe bas d'entr\xE9e":
    description: null
    parameters:
      freq: 800
      order: 2
      type: ButterworthLowpass
    type: BiquadCombo
  Passe bas de sortie:
    description: null
    parameters:
      freq: 2000
      order: 2
      type: ButterworthLowpass
    type: BiquadCombo
mixers:
  Unnamed Mixer 1:
    channels:
      in: 2
      out: 2
    description: null
    mapping:
      - dest: 1
        mute: false
        sources:
          - channel: 0
            gain: 0
            inverted: false
            mute: false
            scale: dB
      - dest: 0
        mute: false
        sources:
          - channel: 0
            gain: 0
            inverted: false
            mute: false
            scale: dB
pipeline:
  - bypassed: null
    channel: 0
    description: null
    names:
      - Limiteur
    type: Filter
  - bypassed: null
    channel: 0
    description: null
    names:
      - "Passe bas d'entr\xE9e"
    type: Filter
  - bypassed: null
    channel: 0
    description: null
    names:
      - Delai
    type: Filter
  - bypassed: null
    channel: 0
    description: null
    names:
      - Convolution
    type: Filter
  - bypassed: null
    channel: 0
    description: null
    names:
      - Passe bas de sortie
    type: Filter
  - bypassed: null
    description: null
    name: Unnamed Mixer 1
    type: Mixer
processors: {}
title: My Favorite Hall
